### ISSUE TITLE
Svelte files are not watched

### ISSUE THREAD

**Issue by antony** [DeMoorJasper/parcel-plugin-svelte#10]
Not sure if this is specific to this plugin or to parcel as a whole, but if I edit say `main.js`, my files are auto-reloaded and I see the changes immediately in the browser. If I edit a `.svelte` component however, they are not.

Should I be raising this here, or in the main project?

**Comment by antony** [comment]
Ah ignore this, it's just that the browser doesn't reload after svelte does. Seems like a parcel issue.

**Comment by DeMoorJasper** [comment]
This probably has to do with how the code is constructed not parcel or parcel-svelte

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by antony** [comment]
You can see a demonstration here: https://github.com/antony/svelte-seed

**Comment by DeMoorJasper** [comment]
I can't see any reason why that demo wouldn't hot reload, strange issue

**Comment by janwillemtulp** [comment]
I am also experiencing the same issue, with the example provided with the `parcel-plugin-svelte` in this repo. I do see that the svelte code is compiled, but the browser does not reload. It does reload when I change html or js files, but not if I change a svelte file.

**Comment by janwillemtulp** [comment]
ah... noticed that it does reload the browser, but not if you just change the HTML template of a sve;te component. It does reload if you change a script in a component...
