### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by 0x13R** [DeMoorJasper/parcel-plugin-svelte#12]
Parcel: 1.7.1
Svelte: 1.64.0
### 🎛 Configuration (.babelrc, package.json, cli command)
[https://github.com/0x13R/parcel-plugin-svelte-issue.git](https://github.com/0x13R/parcel-plugin-svelte-issue.git)
### 🤔 Expected Behavior
Compile successfully.
### 😯 Current Behavior
![image](https://user-images.githubusercontent.com/22267707/38908221-7574f564-42e9-11e8-88f4-393037d1a2be.png)

**Comment by antony** [comment]
Yep I'm getting this error too. I had to roll back to 0.2.1

Btw when you release new versions you aren't creating git tags - might be useful to use `npm version <minor|major|patch>` to get automatic versioning + git tags, so that we can diff the code.

**Comment by DeMoorJasper** [comment]
I'm pretty sure this is the breaking change, I haven't had time to look into this yet however. 22c761b0faeb8b9ca40f1ea5e17fa79802814360

**Comment by DeMoorJasper** [comment]
Should be fixed in the new release

**Comment by antony** [comment]
btw it seems that the current `master` version is `0.2.1` in `package.json` but `npmjs` shows `1.0.0`.

Definitely recommend using `npm version minor|major|patch` as a release strategy to fix this, but just thought you might want to know before you make a new release!

**Comment by DeMoorJasper** [comment]
@antony That's because I did a reset to before the breaking change, I'll fix that before releasing, tnx for letting me know though

**Comment by DeMoorJasper** [comment]
V1.1.0 Has been released and should fix this issue, feel free to open a PR with a test case if it isn't fixed
