### ISSUE TITLE
Don't depend on svelte

### ISSUE THREAD

**Issue by antony** [DeMoorJasper/parcel-plugin-svelte#13]
Svelte v2 has been released, and the syntax is quite different.

I wonder if it makes more sense to, rather than declare a dependency on svelte, leave it to the end user.

I'm making a huge assumption here that nothing in the plugin binds you to svelte v1, or rather, any specific version of svelte.

Thoughts?

**Comment by Rich-Harris** [comment]
FWIW neither rollup-plugin-svelte nor svelte-loader depend on Svelte — instead it's a peerDependency: https://github.com/rollup/rollup-plugin-svelte/blob/master/package.json#L48-L50. They used to depend on it directly and it caused havoc!

**Comment by DeMoorJasper** [comment]
V1.1.0 Has been released and should resolve this issue
