### ISSUE TITLE
Parcel/Svelte: styles are duplicated

### ISSUE THREAD

**Issue by jsonkao** [DeMoorJasper/parcel-plugin-svelte#138]
# 🐛 Bug Report

Styles are being duplicated. In a Svelte component like…

```html
<div></div>>

<style>
  div {
    background: red;
    width: 100px;
    height: 100px;
  }
</style>
```

…DevTools shows these styles:
![image](https://user-images.githubusercontent.com/15334952/80777320-ccdeca80-8b32-11ea-807f-4f32ea0be867.png)

Seems to be related to sveltejs/sapper#1127.

## 🎛 Configuration (.svelterc, package.json, cli command)

package.json:
```
{
  "scripts": {
    "start": "parcel index.html"
  },
  "devDependencies": {
    "parcel-bundler": "^1.12.4",
    "parcel-plugin-svelte": "^4.0.6",
    "svelte": "^3.21.0"
  }
}
```

No extra configuration in Svelte rendering.

## 💻 Code Sample

Example repo: [@jsonkao/svelte-parcel-duplicate-styles](https://github.com/jsonkao/svelte-parcel-duplicate-styles)

**Comment by rondonjon** [comment]
The duplication is not the only problem.

I have tried to use CSS background images in this [Svelte/Parcel template](https://github.com/dafn/svelte-typescript-parcel/issues/5) and couldn't get them to work.

It seems that the image files are copied to the dist folder, but their paths are broken; surprisingly only in *one* of the style copies, and unfortunately in the copy that takes precedence.

![styles](https://user-images.githubusercontent.com/8258823/82690091-e2d83a80-9c5b-11ea-9849-b2ac7855bbd7.png)

**Comment by antony** [comment]
This happened in the official Sapper build for a while, and a really random library upgrade stopped it happening. Might be related.

**Comment by canadaduane** [comment]
Possibly related? https://github.com/parcel-bundler/parcel/issues/2592

**Comment by canadaduane** [comment]
I think I have a solution for this in the Parcel2 transformer that may apply here also (see https://github.com/orlov-vo/parcel-transformer-svelte/issues/8)
