### ISSUE TITLE
Parcel 2

### ISSUE THREAD

**Issue by mathiasrw** [DeMoorJasper/parcel-plugin-svelte#139]
# 🙋 Feature Request

## Detailed description

Would be so lovely to support parcel v2. Its can be used by installing the module parcel@next instead of parcel-bundler

## Similar to an existing solution?

Should work the same way as now (great)

## Possible work-around?

Well... if we downgrade parcel to 1.x it works. 

## Related to a problem?

When I copy all the example code from the readme  but uses parcel@next as bundler I get this when I `yarn start`

```
⚠️  Parser "parcel-plugin-svelte/lib/svelte-asset.js" failed to initialize when processing asset "App.svelte". Threw the following error:
⠋ Building...TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:112:11)    at Object.resolve (path.js:981:7)
    at /Users/mrw/simple/node_modules/parcel/lib/cli.js:88:39
```

**Comment by DeMoorJasper** [comment]
There's a Parcel 2 version already. see https://github.com/orlov-vo/parcel-transformer-svelte

I haven't made it not maintain it and cannot guarantee it'll work at all.
I originally wanted to make it but the name has been taken by this package so hopefully it works 🤷‍♂️

**Comment by mathiasrw** [comment]
@DeMoorJasper I know its sad with the generic svelte transformer plugin name being taken - but if there is any way you feel like taking up the challenge I 100% sure it would storm into the commnity with a plugin named something like `parcel-transformer-svelte-ts` or `parcel-transformer-svelte-plus` that supports parcel 2 and lets you have typescript `<script lang="ts">` and scss `<script lang="scss">` in your files just like https://github.com/dafn/svelte-typescript-rollup
