### ISSUE TITLE
Support for Parcel v2?

### ISSUE THREAD

**Issue by rondonjon** [DeMoorJasper/parcel-plugin-svelte#142]
# 🙋 Feature Request

## Detailed description

Will this plugin support Parcel v2 anytime soon?

The README contains no details about the compatible Parcel versions; I suppose that it is currently targeting Parcel v1 only, as I am getting errors when trying to build .svelte files with Parcel v2?

**Comment by DeMoorJasper** [comment]
This plugin is for parcel 1, there's a parcel 2 version already https://yarnpkg.com/package/parcel-transformer-svelte 

Not entirely sure how reliable this transformer is. Might add one to the parcel monorepo at some point if it appears to be unreliable as Svelte seems like it's starting to get pretty common

**Comment by rondonjon** [comment]
Thanks for the link @DeMoorJasper :+1: 

As a quick follow-up, maybe also for other readers:

I have added the transformer to a Parcel v2 setup, but there seems to be a conflict with the latest Parcel v2 version (source map format has changed).

There seem to be two other transformers with similar names and the same goal:

 * https://www.npmjs.com/package/parcel-transformer-sveltejs
 * https://github.com/22mahmoud/parcel-transformer-svelte3

While the prior crashes the build with the same error about source maps, the build completes with the latter, but then at runtime the app raises an exception about missing exports from the Svelte files.

:man_shrugging:

**Comment by DeMoorJasper** [comment]
@rondonjon thanks for looking into it so there's 3 svelte plugins that are all broken, well that's not good, that pretty much takes away all possible plugin names except scoped ones.

Currently I'm pretty focused on getting Parcel 2 to beta and stable like the rest of the parcel team but once I have more time on the side I might look into porting svelte to Parcel 2 and perhaps even make it an official parcel plugin

**Comment by canadaduane** [comment]
FWIW, I  spent some time trying to get other parcel 2 transformers for Svelte working:

- `parcel-transformer-svelte`: Incorrectly uses `async getConfig` (should be `async loadConfig` AFAICT); duplicate CSS issues; HMR not working correctly
- `parcel-transformer-sveltejs`: Copy of parcel-transformer-svelte; published on NPM; the github repository has been deleted
- `parcel-transformer-svelte3`: Repository has been archived by the owner. Read-only.

I'm currently trying to learn how to fix the issues with `parcel-transformer-svelte`, making PRs as I discover solutions (but I'm not an expert in Parcel).

**Comment by canadaduane** [comment]
I made a PR to https://github.com/orlov-vo/parcel-transformer-svelte and it was accepted. Looks like it is being maintained.

**Comment by DeMoorJasper** [comment]
in that case I can close this...
