### ISSUE TITLE
Example for using Typescript with parcel-plugin-svelte?

### ISSUE THREAD

**Issue by remast** [DeMoorJasper/parcel-plugin-svelte#144]
Hi,

I tried to use Typescript in my Svelte project thats based on the parcel plugin for svelte. Yet I could not figure out how I have to configure the preprocessing for Typescript. Does anyone have a working example for me?

Thanks  a lot,
Jan

**Comment by surajbarkale** [comment]
I installed `svelte-preprocess` and added following `svelte.config.js` to get typescript support working:
```js
const autoPreprocess = require('svelte-preprocess');

module.exports = {
    preprocess: autoPreprocess()
}
```
It would be good to have auto detection for `svelte-preprocess` if possible.

**Comment by remast** [comment]
Thanks, I got it working!
