### ISSUE TITLE
 This plugin doesn't work since Svelte 3.29.5

### ISSUE THREAD

**Issue by Milesq** [DeMoorJasper/parcel-plugin-svelte#153]
# 🐛 Bug Report

## 🌍 Environment
Svelte 23.29.5 or higher, the latest version of parcel-bundler

**Comment by Milesq** [comment]
`$ parcel build src/index.html
‼  Parser "parcel-plugin-svelte\lib\svelte-asset.js" failed to initialize when processing asset "src\App.svelte". Threw the following error:
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './compiler.js' is not defined by "exports" in (...)\node_modules\svelte\package.json`

**Comment by Milesq** [comment]
I didn't read the mistake very well so it took me more time. The package.json of the Svelte library contains the "exports" key which doesn't allow importing files other than those listed inside. Svelte devs allowed us to import things from the compiler file, but we must reference it with `svelte/compiler` instead of `svelte/compiler.js`

**Comment by DeMoorJasper** [comment]
Released in 4.0.8

**Comment by fregante** [comment]
Can you publish 4.0.8? npm Still has 4.0.6

**Comment by emirotin** [comment]
That's true, it can be installed directly but the tag is not moved so this version is not picked automatically by the install/upgrade command

**Comment by joanrieu** [comment]
Please publish it, it still isn't picked up by default on npm to this day.
