### ISSUE TITLE
Publish 4.0.8 as latest on NPM

### ISSUE THREAD

**Issue by XAMPPRocky** [DeMoorJasper/parcel-plugin-svelte#168]
https://github.com/DeMoorJasper/parcel-plugin-svelte/issues/153 is still an issue if you use `npm install`, which makes it quite frustrating experience as a first time user as I couldn't figure out what was wrong with the fresh setup.

**Comment by DeMoorJasper** [comment]
Oh my release script appears to be incorrect, will fix this tomorrow and release a new version, sorry for any inconvenience and thanks for letting me know. For now you can try the next tag or explicitly set the version in pkg.json
