### ISSUE TITLE
How to import nested component

### ISSUE THREAD

**Issue by andruschka** [DeMoorJasper/parcel-plugin-svelte#2]
Hey nice work for creating this plugin!  
But I am not able to import a component inside a component...  
Getting `Cannot find module './header.svelte'` in the browser console ...

**Comment by DeMoorJasper** [comment]
Could u upload an example that uses this?
Than i could look into it and fix it

**Comment by andruschka** [comment]
Hey, yes i have a main.js file (which is imported with a <scrtip> tag in the index.html) and this file imports the App.svelte file and then initializes the App component. The App.svelte looks like this:
```
<Header></Header>

<script>
import Header from './header.svelte'
export default {
  components: { Header }
}
</script>
```
Really basic setup where I just want to import another component inside of the root component

**Comment by andruschka** [comment]
app.svelte and header.svelte are ofcourse located in the same dir.

**Comment by DeMoorJasper** [comment]
Tnx for letting me know the exact setup, i'll look into it and see if i can fix it

**Comment by DeMoorJasper** [comment]
It should be fixed in the new release @andruschka 
Thank you for reporting this :)

**Comment by andruschka** [comment]
cool 👍

**Comment by andruschka** [comment]
So - it is only working with `--no-cache` flag - am I right?

**Comment by DeMoorJasper** [comment]
Ow no that that was just for testing, you should however remove the old cache and update the plugin.
After that it should work both with and without caching enabled
