### ISSUE TITLE
<ComponentName> is not a constructor when nesting components

### ISSUE THREAD

**Issue by antony** [DeMoorJasper/parcel-plugin-svelte#20]
# 🐛 Bug Report

## 🎛 Configuration (.svelterc, package.json, cli command)

```json
  "devDependencies": {
    "parcel-bundler": "^1.8.1",
    "parcel-plugin-svelte": "^1.1.6",
    "svelte": "^2.7.0"
  }
```

command:

```bash
    "start": "parcel --log-level 3 ./index.html"
```

## 💻 Code Sample

Seems to reproduce every time I edit any part of the project. The first time I start the parcel process, it compiles, and then making a change or stopping + starting the parcel process, causes the project to stop working, and the following error to be shown in the console:

![problem](https://user-images.githubusercontent.com/218949/40688773-43190348-6397-11e8-9e46-30d6baecd179.png)

The problem is that to resolve this error so that I can continue working, I need some sort of combination of:

* commenting out its usage in the parent componentre
* deleting it and recreating it
* renaming the component and all its uses to something else
* deleting the `.cache` directory

but there is no definitive combination which appears to fix it. It's basically impossible to work on my project now.

## 🌍 Your Environment

See svelte + parcel version above
Ubuntu Linux 17.10

## Project to reproduce

I've created a [simple example project](https://github.com/antony/parcel-plugin-svelte-bug).

**Comment by DeMoorJasper** [comment]
Is this fixed with v1.2.0, now it supports hot reload properly :)

**Comment by antony** [comment]
Sounds promising! I'll give it a go.

**Comment by antony** [comment]
Looks like this works well! Awesome work :tada:

**Comment by antony** [comment]
It's back :(

Seems to be the first component you `import` somehow gets incorrectly compiled, and breaks the bundle. Even if you never use that component.

**Comment by DeMoorJasper** [comment]
Could you create a repro?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by antony** [comment]
The same repro from before should produce it - it's hard to say exactly what reproduces it, but once you hit it it's impossible to get rid of, removing `.cache` and `dist` and running build, watch, you name it, and I can't get the project to work again - total killer.

**Comment by antony** [comment]
I `git pull && npm i` and `npm run start` the project I made above. First you get this error:

https://github.com/parcel-bundler/parcel/issues/1319

So you Ctrl+C and then run `npm run start` again, and then you get this:

![no-clue](https://user-images.githubusercontent.com/218949/41061342-2c9b01fa-69ca-11e8-8d90-d0992157fd7a.png)

As I mentioned before... YMMV with recreating this, but try editing the components a bit in watch mode and it should break pretty quickly.

**Comment by DeMoorJasper** [comment]
Ow alright I'll look into it as soon as I get some time
