### ISSUE TITLE
Path issues on windows

### ISSUE THREAD

**Issue by tivac** [DeMoorJasper/parcel-plugin-svelte#25]
# 🐛 Bug Report

These lines

https://github.com/DeMoorJasper/parcel-plugin-svelte/blob/c1325baffe160037dedfcd51e94cd6d143d2f83c/src/SvelteAsset.js#L7-L11

output a string with `\` in it on windows, which leads to errors like this from Parcel.

```
C:\Users\Patrick\Documents\Code\svelte-xstate>npm start

> svelte-xstate@1.0.0 start C:\Users\Patrick\Documents\Code\svelte-xstate
> parcel src/index.html --no-hmr

Server running at http://localhost:1234
×  C:\Users\Patrick\Documents\Code\svelte-xstate\src\app.svelte:221:54: Cannot resolve dependency '..
ode_modulesparcel-plugin-sveltesrchot-api.js' at 'C:\Users\Patrick\Documents\Code\svelte-xstate\src\..
ode_modulesparcel-plugin-sveltesrchot-api.js' at 'C:\Users\Patrick\Documents\Code\svelte-xstate\src\..
ode_modulesparcel-plugin-sveltesrchot-api.js'
    at Resolver.resolve (C:\Users\Patrick\Documents\Code\svelte-xstate\node_modules\parcel-bundler\src\Resolver.js:70:17)
    at <anonymous>
```

Note how `node_modules\parcel-plugin\svelte\src\hot-api.js` became `ode_modulesparcel-plugin-sveltesrchot-api.js` because it used window-style slashes instead of *nix-style slashes.

Running the path from line 7 through something like [`slash`](https://www.npmjs.com/package/slash) is probably worthwhile. I wasn't able to get this working on Windows despite passing `--no-hmr` so I'm unable to use this plugin currently.

## 💻 Code Sample

Use the example in the repo

## 🌍 Your Environment

```json
"devDependencies": {
    "parcel-bundler": "^1.9.2",
    "parcel-plugin-svelte": "^1.2.1",
    "svelte": "^2.7.2"
  },
```

`npm @6.1.0`
`node@8.11.2`

Running on Windows 10

**Comment by DeMoorJasper** [comment]
I'll do a regex replace for backwards slashes, thank you for reporting :)
