### ISSUE TITLE
HMR causes component styles to disappear

### ISSUE THREAD

**Issue by antony** [DeMoorJasper/parcel-plugin-svelte#30]
# 🐛 Bug Report

HMR works but loses inline styles until you refresh the whole page.

## 🎛 Configuration

See https://github.com/beyonk-adventures/svelte-parcel-hmr-issue

## 💻 Code Sample

See https://github.com/beyonk-adventures/svelte-parcel-hmr-issue

If you `npm i` then `npm run dev` you will see the time, in green, in realtime.

If you then change the component's CSS to 'red' rather than 'green', you will actually lose all component defined styles until you refresh the page (font will become normal instead of bold, and black).

Upon refresh your style will have updated and you will see the time in red.

Worth noting - this might be caused by the fix for the other issue #15 whereby multiple css files added to parcel's tree were causing styles to be overwritten.

## 🌍 Your Environment

See package.json for versions
Ubuntu 18.10
Chrome Version 68.0.3440.106 (Official Build) (64-bit)

**Comment by antony** [comment]
Heya - any progress on figuring out what this is yet? I'd love to start using Parcel again!

If there's anything you need me to do, please let me know how I can help :)

**Comment by DeMoorJasper** [comment]
@antony I’ve been quite busy lately with other things. Hopefully I can figure this out soonish. This will probably be fixed once parcel 2 is released

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by antony** [comment]
@DeMoorJasper no problems - me too! Looking forward to Parcel 2 :)

**Comment by antony** [comment]
@adamhepton This fixes it! Wow! I can't thank you enough!

This needs to be in the docs. I'll open a PR.
