### ISSUE TITLE
Support .html imports

### ISSUE THREAD

**Issue by DeMoorJasper** [DeMoorJasper/parcel-plugin-svelte#4]
Waiting on parcel to add any way to do this without overwriting the default html asset processing, as this would break any html file

**Comment by acstll** [comment]
Is there any issue opened in parcel-bundler/parcel we could watch?

**Comment by DeMoorJasper** [comment]
I'm pretty sure there is an issue regarding this.
There is also an issue and PR regarding a plugin architecture rewrite, which will probably improve extendibility soonish. So once either the html fil or new plugin system lands i'll update this plugin

**Comment by EliSnow** [comment]
This was closed but appears to still be an issue. Is this not fixable?

**Comment by DeMoorJasper** [comment]
@EliSnow this will be fixed with the rework of this plugin for Parcel 2. So it won't be fixed in this plugin untill than.

**Comment by EliSnow** [comment]
Ok, I'm glad it's still on the radar. In the meantime...

(I'll preface this by saying I don't know much about parcel plugins and the precedence used when resolving file extensions)

Would it be possible to add support for a `.svelte.html` extension? Perhaps add:

```js
bundler.addAssetType('svelte.html', require.resolve('./svelte-asset.js'));
```

to [main.js](https://github.com/DeMoorJasper/parcel-plugin-svelte/blob/master/packages/parcel-plugin-svelte/src/main.js)?

**Comment by DeMoorJasper** [comment]
I'm pretty sure that doesn't work with Parcel atm, will also be fixed with Parcel 2.
