### ISSUE TITLE
Doesn't work with global parcel install

### ISSUE THREAD

**Issue by jwhazel** [DeMoorJasper/parcel-plugin-svelte#41]
# 🐛 Bug Report
Hi. Feel free to close this if I'm missing something simple or I'm just misinformed on the scope of this project. But I typically run parcel as a global install. It took me a while to figure out why I couldn't get this plugin to work properly. I finally stumbled across a sample repo and discovered the fact that parcel itself has to be installed locally.

## 💻 Code Sample

https://github.com/antony/svelte-seed
^try cloning this and doing `npm run dev`. Note that it works. Now try doing `npm remove parcel-bundler` and running it (assuming you have parcel installed globally). It results in the following error:

```
🚨  svelte-seed/src/main.js:1:16: Cannot resolve dependency './components/app/component.svelte' at /dev/testing/svelte-seed/src/components/app/component.svelte'
> 1 | import App from './components/app/component.svelte'
    |                ^
  2 | 
  3 | const app = new App({
  4 |   target: document.body,
```

Nothing else has changed other than where parcel is being invoked from (i.e. the component path is still correct despite saying it can't be resolved). I suspect this is not expected behavior but looking for some input.

## 🌍 Your Environment

OSX 10.14.3
Node 11.3.0
Parcel 1.11.0
Parcel-plugin-svelte: 2.1.0-alpha-0
Svelte 2.15.3

**Comment by DeMoorJasper** [comment]
Hey, unfortunately I won’t have the time to look into this. If anyone wants to debug this further feel free to do so. I’m only addressing critical bugs atm as Parcel 2 is getting closer everything and a rewrite of this plugin is gonna happen anyway when this gets out. However this plugin is still being actively developed and a second alpha should come out soon. That hopefully has better support for the new svelte

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
