### ISSUE TITLE
Unrecognized option 'store'

### ISSUE THREAD

**Issue by MightyRevenge** [DeMoorJasper/parcel-plugin-svelte#42]
# 🐛 Bug Report
While trying to compile with Parcel, I get this error for `App.svelte` and I'm unsure what it's referring to...

## 🎛 Configuration (.svelterc, package.json, cli command)

no configuration!

## 💻 Code Sample

I only have 2 files, `main.js`: 
```
import App from './App.svelte';

const app = new App({
	target: document.body,
	props: {
		name: 'world'
	}
});

window.app = app;

export default app;
```

and `App.svelte`:
```
<script>
	export let name;
</script>

<style>
	h1 {
		color: purple;
	}
</style>

<h1>Hello {name}!</h1>
```

`package.json`:
```
{
  "name": "test-svelte-app-parcel",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "dev": "parcel src/main.js",
    "build": "parcel build src/main.js"
  },
  "devDependencies": {
    "parcel-bundler": "^1.12.3",
    "parcel-plugin-svelte": "^2.1.0-alpha-0"
  },
  "dependencies": {
    "svelte": "^3.0.0"
  }
}
```

## 🌍 Your Environment

svelte: ^3.0.0
parcel-bundler: ^1.12.3

**Comment by DeMoorJasper** [comment]
Svelte 3 is not fully supported yet, the alpha was for the svelte 3 alpha but haven’t had time to update it yet

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by okrad** [comment]
Hi, 
I think the problem lies on the fact that the 2.1.0-alpha-0 version (the last published on npm ATM) is not updated with the latest on github. The problem seems to be a "store" property that get passed as a  compiler option:

**Local version in node_modules/parcel-plugin-svelte/src/svelte-asset.js**
```
let defaultOptions = {
   generate: 'dom',
   store: true,
   css: true,
   format: major_version >= 3 ? 'esm' : 'es'
};
```

**Github version**

```
let defaultOptions = {
  generate: 'dom',
  css: true
};

let customCompilerOptions = config.compilerOptions || {};

if (major_version >= 3) {
  defaultOptions.format = 'esm';
  defaultOptions.sveltePath = 'svelte';
} else {
  defaultOptions.format = 'es';
  defaultOptions.store = true;
  defaultOptions.shared = 'svelte/shared.js';
}

```
As a temp patch I modified the code in node_modules/parcel-plugin-svelte/src/svelte-asset.js this way (row 46):

```
    let defaultOptions = {
      generate: 'dom',
      css: true,
      format: major_version >= 3 ? 'esm' : 'es',
      sveltePath: 'svelte'
    };

```
and it seems to work correctly...

**Comment by DeMoorJasper** [comment]
I've just published v3 of this plugin. It might not work.
It's still a beta. Just didn't wanna append it with `-beta-0`

**Comment by okrad** [comment]
Thank you @DeMoorJasper.
I tried your svelte-3-example: now the application compiles without errors, but then (as you warned) I get this error in the devtools console:
```
TypeError: "class constructors must be invoked with |new|"
    App App.svelte:116
    _register proxy.js:128
    proxyComponent proxy.js:54
    parcelRequire<["src/main.js"]< main.js:3
    newRequire main.1e43358e.js:47
    parcelRequire main.1e43358e.js:81
    <anonymous> main.1e43358e.js:8
```

If I can help you in any way let me know.

**Comment by DeMoorJasper** [comment]
@okrad I’m aware of this issue and will try to look into it. If anyone has experience with Svelte compiler or just wants to try to fix this feel free to do so.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
