### ISSUE TITLE
When calling onMount, afterUpdate, etc. receiving "Uncaught Error: Function called outside component initialization"

### ISSUE THREAD

**Issue by auderer** [DeMoorJasper/parcel-plugin-svelte#46]
# 🐛 Bug Report

When calling lifecycle methods such as `onMount`, `afterUpdate`, etc., I receive the following error and nothing is rendered:
```
internal.mjs:520 Uncaught Error: Function called outside component initialization
    at get_current_component (internal.mjs:520)
    at afterUpdate (internal.mjs:533)
    at instance (Engine.svelte:82)
    at init (internal.js:1374)
    at new Engine (Engine.svelte:112)
    at create_fragment (App.svelte:14)
    at init (internal.js:1385)
    at new App (App.svelte:49)
    at Object.parcelRequire.main.js../App.svelte (main.js:3)
    at newRequire (main.1f19ae8e.js:47)
```

## 🎛 Configuration (.svelterc, package.json, cli command)

`package.json`:
```json
{
  "name": "svelte-3-example",
  "main": "index.html",
  "version": "3.0.0",
  "license": "MIT",
  "private": true,
  "scripts": {
    "start": "parcel index.html --no-cache --no-hmr"
  },
  "dependencies": {
    "parcel-bundler": "^1.11.0",
    "parcel-plugin-svelte": "^3.0.0",
    "svelte": "^3.0.0"
  },
  "browserslist": [
    "last 1 chrome versions"
  ]
}
```

## 💻 Code Sample

`App.svelte`:
```html
<p>
  Hello { name }, the time is <span class="the-time">{ hours }:{ minutes }:{ seconds }</span>
</p>

<style>
  .the-time {
    font-weight: bold;
  }
</style>

<script>
	import { onMount } from 'svelte'
	
	export let name = 'Anonymous'
	let time = new Date()
	
	onMount(() => {
		const timer = setInterval(() => {
			time = new Date()
		}, 1000)
		
		return () => {
			clearInterval(timer)
		}
	})
	
	let hours, minutes, seconds
	
	$: {
		hours = time.getHours()
		minutes = time.getMinutes()
		seconds = time.getSeconds()
	}
</script>
```

`main.js`:
```js
const App = require('./App.svelte');

const app = new App({
  target: document.getElementById('demo'),
  data: {
    name: 'world'
  }
});
```

## 🌍 Your Environment

Svelte: 3.0.0
Parcel: 1.11.0
Parcel Plugin Svelte: 3.0.0

**Comment by henrikhermansen** [comment]
The issue still exists with the latest versions right now.

I'm out on thin ice here, but I did a little digging. I used a very simple app - all my Svelte file does is call `onMount` with a function that runs `console.log()`
First, take a look at the stack trace
```
...
at afterUpdate (internal.mjs:533)
...
at init (internal.js:1374)
...
```
Wait! Two files named internal, but with different extensions?

Looking at [Svelte REPL](https://svelte.dev/repl) sources (in dev tools), you will find its `node_modules/svelte` only contains `internal.mjs`, while our Parcel-bundled apps indeed contains both.

So I tried manually deleting my `internal.js`. Now my app runs just fine!
I also tried re-installing and deleting `internal.mjs`. Again, it works!

I don't know enough about which part of the Parcel bundling is responsible for including these files from Svelte in the build, but it sure seems something is causing Parcel to doubling up on which files to use.
While I don't know how to fix this, I sure hope this little research might help someone else come up with a solution.

**Comment by henrikhermansen** [comment]
Since Svelte recently separated the files into subdirectories the rimraf trick does no longer work.
Instead, I threw together some javascript you can put in a js-file and run postinstall with node.
`"postinstall": "node clean-svelte.js"`
https://gist.github.com/henrikhermansen/6fb6d9bd132eb1056cae7b712e7bf411
Note that this code uses fs promises, which requires Node v10. Just rewrite it with callbacks, or even sync functions, to make it work for older Node.

**Comment by silentworks** [comment]
I've tested this on the latest version of this plugin and its all working fine. Please also make sure svelte is installed as a devDependency and not an actual dependency. Svelte itself should never be bundled with your application code.
