### ISSUE TITLE
Parcel cache

### ISSUE THREAD

**Issue by dmitrykurmanov** [DeMoorJasper/parcel-plugin-svelte#47]
# (question)

## Detailed description

In your [example](https://github.com/DeMoorJasper/parcel-plugin-svelte/blob/128ecd1a023ab366d1a65ce69059f4dd75dcaf51/svelte-3/svelte-3-example/package.json#L8) there is `--no-cache` cli parameter. 

Is it possible to use the **parcel cache** with the **parcel-plugin-svelte** ?

Thanks for your work!

**Comment by DeMoorJasper** [comment]
Yes it's possible to use cache with the plugin.

The reason cache is disabled in the example:
The example is sometimes used for testing and plugin changes only invalidate cache if the version number changes which doesn't happen in development.
