### ISSUE TITLE
Broken hot reload when using workaround for #44

### ISSUE THREAD

**Issue by zastrowm** [DeMoorJasper/parcel-plugin-svelte#49]
# 🐛 Workaround Report for #44 

Like issue #44, I got the `Class constructor SvelteComponent cannot be invoked without 'new'` error; applying the workaround mentioned for a modern browser via `browserslist`:

```
"browserslist": [
    "edge >= 13"
  ]
```

gets things working in parcel, but as [comment on #44](https://github.com/DeMoorJasper/parcel-plugin-svelte/issues/44#issuecomment-487211932) mentions, it completely breaks HMR.

Looking at `svelte-asset.js` I found that if you *stop* calling `makeHot`, then the browser refreshes as normal.

i.e. remove these lines:

https://github.com/DeMoorJasper/parcel-plugin-svelte/blob/e0ee9a391546a27c9c6ac2f343ab9c1b38feb541/packages/parcel-plugin-svelte/src/svelte-asset.js#L86-L88

And then modifying a `svelte` file **does** refresh the browser.

## 🌍 Your Environment

- Windows OS
- parcel-bundler: 1.12.3
- svelte: 3.4.2

**Comment by samuelgozi** [comment]
A temporary solution would be to turn off HMR entirely by adding the `--no-hmr` flag to the parcel command.
I will add a pull request for a fix later today.
