### ISSUE TITLE
Support svelte store configuration

### ISSUE THREAD

**Issue by naturalethic** [DeMoorJasper/parcel-plugin-svelte#5]
If there is no significant cost to adding the `store: true` option to the Svelte compilation options, perhaps its fine then to always enable it.

**Comment by DeMoorJasper** [comment]
I'm not aware what store exactly is being used for, i'll probably enable it once i figure out what it exactly does

**Comment by naturalethic** [comment]
Its the state manager built in to svelte.  https://svelte.technology/guide#state-management

**Comment by DeMoorJasper** [comment]
It seems like it can’t hurt to enable by default i’ll add it tomorrow

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DeMoorJasper** [comment]
Should be up in the new version both on npm and this repository 👍

**Comment by naturalethic** [comment]
Great!
