### ISSUE TITLE
Nested import error: TypeError: "header.$$ is undefined".

### ISSUE THREAD

**Issue by Janealter** [DeMoorJasper/parcel-plugin-svelte#55]
# 🐛 Bug Report

Nested import error: `TypeError: "header.$$ is undefined"`.
Without import app works normally, with import I get this error.

## 🎛 Configuration

```
{
  "name": "sveltetest",
  "version": "1.0.0",
  "description": "",
  "main": "index.html",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "browserslist": [
    "last 1 chrome versions",
    "last 1 firefox version"
  ],
  "author": "Janealter",
  "license": "ISC",
  "devDependencies": {
    "@babel/polyfill": "^7.4.4",
    "parcel-bundler": "^1.12.3",
    "parcel-plugin-svelte": "^3.0.1",
    "svelte": "^3.4.4"
  }
}
```
Commands:
`./node_modules/parcel-bundler/bin/cli.js index.html --no-cache`;
`./node_modules/parcel-bundler/bin/cli.js index.html`;
`parcel index.html`;
`parcel index.html --no-cache`

## 💻 Code Sample

*./index.html*
```html
<!DOCTYPE html> 
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Svelte Test</title>
  </head>
  <body>
    <main></main>
    <script src="src/index.js"></script>
  </body>
</html>
```

*./src/index.js*
```js
import '@babel/polyfill';
import App from './App';

const app = new App({
  target: document.querySelector('main'),
  data: {},
});
```

*./src/App.svelte*
```html
<script>
  import Header from './components/Header';

  const name = 'Test';
</script>

<p>{name}</p>
<Header/>
```

*./src/components/Header.svelte*
```html
<header>
  <p>Test text</p>
</header>
```

## 🌍 Your Environment

Svelte 3.4.4, Parcel 1.12.3

**Comment by orlov-vo** [comment]
It seems like a bug with proxing of internal field `$$` in [`svelte-dev-helper`](https://github.com/ekhaled/svelte-dev-helper/blob/master/lib/proxy.js).

**Comment by hectorlf** [comment]
Just in case this helps, as it is not explicitly mentioned. I'm seeing:

TypeError: Cannot read property 'fragment' of undefined
    at Object.c (Hello.svelte:117)

With the most simplest nested component. The thing is that this only happens when using the embedded server, running parcel build generates a correct output.

parcel: 1.12.3
parcel-plugin-svelte: 3.0.1
svelte: 3.6.3

**Comment by google-mac** [comment]
I'm getting this as well. It's a basic implementation of Svelte with Parcel and this plugin for Svelte. The app works fine until I import a component and I get `TypeError: "counter.$$ is undefined"`.

**Comment by hibas123** [comment]
Yes, I get the same error. In my case it also seems that the `svelte-dev-helper `causes that problem.

**Comment by b12f** [comment]
I'm getting the same issue with Webpack and resolved it after setting `devServer.hot` from `true` to `false`.

**Comment by orlov-vo** [comment]
yes, it’s problem related with HMR. you can use simple workaround with disabling hot reloading: ‘parcel —no-hmr index.html’

**Comment by mlabbe** [comment]
I'm getting this as well, and it can be reproduced using exactly the contents of the svelte.dev tutorial:
https://svelte.dev/tutorial/nested-components

**Comment by wenerme** [comment]
But who response to resolve this issues ? `--no-hmr` is a work around, very unfriendly to dev.
