### ISSUE TITLE
Components give errors when first imported

### ISSUE THREAD

**Issue by jumpinggoofballs** [DeMoorJasper/parcel-plugin-svelte#7]
**parcel-bundler (global), parcel-plugin-svelte (dev), svelte-router (dev**)

I have an example here: [](https://github.com/jumpinggoofballs/parcel-svelte-routing-example)

When I run that as per the description I get this: 

> Uncaught TypeError: createRouter is not a function

If I comment out all the svelte-router stuff then I get similar errors:

> Uncaught TypeError: Page1 is not a constructor

However, if I comment all the imports and their references out, then it works. 

And **then**, if I add them back one by one without turning off the development server they start working as intended. What is going on here?

**Comment by DeMoorJasper** [comment]
Can u set up some kind of test environment?

**Comment by jumpinggoofballs** [comment]
Ahh... 

Turns out the error was that I had to have parcel-bundler installed as a dev dependency as well as globally. 

Apologies for the confusion. Maybe include this in the documentation for the plugin?

Regards.
