### ISSUE TITLE
Console warnings appear in production but not in dev

### ISSUE THREAD

**Issue by bdoms** [DeMoorJasper/parcel-plugin-svelte#91]
# 🐛 Bug Report

## 🎛 Configuration (.svelterc, package.json, cli command)

With the default config - which should default to `svelte: {dev: false}` according to the docs (https://svelte.dev/docs#svelte_compile) - I am not seeing any `console.warn` calls coming from Svelte in development when it's serving locally via a websocket and hot reload. However, when I run `parcel build` and use the output JS file like I do in production, then a bunch of warnings I didn't know about appear.

I believe this is backwards from what it should be, and I think the issue is this line (https://github.com/DeMoorJasper/parcel-plugin-svelte/blob/master/packages/parcel-plugin-svelte/lib/svelte-asset.js#L17):

```js
dev: this.options.production
```

I'm betting there's supposed to be a `!` in there to negate it.

Even if that's not the case, in development my console is clear, but in production I'm seeing things like `<Component> was created without expected prop 'prop'` and `<Component> was created with unknown prop 'prop'`

## 🌍 Your Environment

On Svelte 3.9.2, Parcel 1.12.3, and plugin 4.0.3

This plugin has been really useful! Let me know what else I can do to help.

**Comment by DeMoorJasper** [comment]
Ow yes it should be !options.production will update it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DeMoorJasper** [comment]
Fixed in v4.0.4
