### ISSUE TITLE
How to apply scss...?

### ISSUE THREAD

**Issue by hmmhmmhm** [DeMoorJasper/parcel-plugin-svelte#93]
Has anyone succeeded in applying it?

**Comment by DeMoorJasper** [comment]
Could you give some code examples or something? There are people who use css with this plugin not sure how scss would/should work. Maybe I can help out or even implement it if it's not already in there.

**Comment by hmmhmmhm** [comment]
@DeMoorJasper 
![스크린샷 2019-11-21 오전 11 34 05](https://user-images.githubusercontent.com/38493722/69299039-e78f4800-0c52-11ea-85c5-23e6bed2af3e.png)

I modified the settings as above, but it doesn't apply at all.

![스크린샷 2019-11-21 오전 11 35 08](https://user-images.githubusercontent.com/38493722/69299099-0ee61500-0c53-11ea-9fbc-b40a2bc11f52.png)

My parcel bundleer settings are as above.
What can I do if my settings in svelte.config.js don't apply at all?

**Comment by hmmhmmhm** [comment]
![스크린샷 2019-11-21 오후 12 02 48](https://user-images.githubusercontent.com/38493722/69300570-ea8c3780-0c56-11ea-8b73-2aa92244d8bd.png)

I'm so sorry. It was my fault,
I applied the above settings to package.json, I didn't felt something wrong.
After clearing the above settings, the settings of svelte.config.js were applied properly.
