### ISSUE TITLE
Does not watch for imported scripts and styles

### ISSUE THREAD

**Issue by JakubKoralewski** [DeMoorJasper/parcel-plugin-svelte#96]
# 🐛 Bug Report

Does not update when I change the the `script.ts` or `style.scss` files. Updates them if I also unnecessarily import those files inside the `index.html` file.

## 🎛 Configuration (.svelterc, package.json, cli command)

Windows WSL
cli: `rm -rf dist && parcel src/index.html`

```ts
\\ index.ts
import Svelte from './index.svelte';
new Svelte({
	target: document.body
});
```

```html
<!-- index.html -->
<html lang="en">
	<head>
		<title>Go go go! Go A no go B!</title>
		<link rel="stylesheet" href="style.scss">
	</head>
	<body>

	<script src="index.ts"></script>
	</body>
</html>
```

```svelte
// index.svelte
<style lang="scss" global>
	@import './style.scss';
</style>

<script lang="ts" src="script.ts">
</script>
```

package.json:
```json
    "parcel-bundler": "^1.12.4",
    "parcel-plugin-svelte": "^4.0.5",
    "postcss-modules": "^1.4.1",
    "svelte": "^3.16.5",
    "svelte-preprocess": "^3.3.0"
```

**Comment by DeMoorJasper** [comment]
This is strange, I'll look into this when I find the time. Maybe tomorrow

**Comment by JakubKoralewski** [comment]
I'll try to create a minimal repo when I have the time if you can't reproduce 🤞

**Comment by JakubKoralewski** [comment]
@DeMoorJasper while initially getting Svelte and Parcel to work I bumped into #44, then followed https://github.com/DeMoorJasper/parcel-plugin-svelte/issues/44#issuecomment-487211932 these instructions and forgot about it. Rebumped into it when creating the example repo.

Seems like a duplicate :/
